PL = { 
'Invisible Ghost', 
'The Lost Jungle', 
'Parlor, Bedroom and Bath', 
'He Walked by Night', 
'Last Woman on Earth', 
'Assassin of Youth', 
'Bela Lugosi Meets a Brooklyn Gorilla', 
'Flash Gordon Conquers the Universe', 
'Great Guy', 
'Gumbasia', 
'Minnie Mouse#Minnie.27s Yoo Hoo', 
'The Ape Man', 
'Bowery at Midnight', 
'Midnight Manhunt', 
'Wackiki Wabbit', 
'Angel and the Badman', 
'The Birth of a Nation', 
'Teenage Zombies', 
'The Flying Deuces', 
'Boys Beware', 
'A Bucket of Blood', 
'The Amazing Transparent Man', 
'Revolt of the Zombies', 
'The Fatal Hour', 
'Hemp for Victory', 
'House on Haunted Hill', 
'Radar Men from the Moon', 
'Dick Tracy Meets Gruesome', 
'Sing a Song of Six Pants', 
'The Great Alaskan Mystery', 
'The Killer Shrews', 
'Black Dragons', 
'Man with a Movie Camera', 
'The Corpse Vanishes', 
'Road to Bali', 
'They Made Me a Criminal', 
'Hercules and the Tyrants of Babylon', 
'Teenagers from Outer Space', 
'Reefer Madness', 
'The New Adventures of Tarzan', 
'Child Bride', 
'The Incredible Petrified World', 
'The Wabbit Who Came to Supper', 
'The Screaming Skull', 
'The Phantom Empire', 
'The Monster Walks', 
'Check and Double Check', 
'His Girl Friday', 
'Second Chorus', 
'The Hitch-Hiker', 
'Snafuperman', 
'Happy Go Lovely', 
'Voyage to the Planet of Prehistoric Women', 
'Meet John Doe', 
'Night of the Living Dead', 
'All This and Rabbit Stew', 
'The Mad Monster', 
'Glamour Gal', 
'Hercules vs. the Moon Men', 
'The Manster', 
'The Brother from Another Planet', 
'Christmas Comes But Once a Year', 
'Nightmare Castle', 
'Poor Cinderella', 
'Why We Fight', 
'The Lodger: A Story of the London Fog', 
'Horrors of Spider Island', 
'Crash of the Moons', 
'The Incredible 2-Headed Transplant', 
'The Hurricane Express', 
'Penny Serenade', 
'Terror by Night', 
'Three Came Home', 
'A Day at the Zoo', 
'Nosferatu', 
'Malice in the Palace', 
'Attack of the Giant Leeches', 
'Broken Blossoms', 
'The Outlaw', 
'The Vampire Bat', 
'Fresh Hare', 
'A Shriek in the Night', 
'Experiments in the Revival of Organisms', 
'Spring in a Small Town', 
'Mr. Robinson Crusoe', 
'The Princess and the Pauper', 
'Fear in the Night', 
'Stamp Day for Superman', 
'Our Gang Follies of 1938', 
'The Chicken of Tomorrow', 
'The Battleship Potemkin', 
'Africa Screams', 
'Holy Ghost People', 
'Scared to Death', 
'Perversion for Profit', 
'Dead Men Walk', 
'Scarlet Street', 
'Indestructible Man', 
'Royal Wedding', 
'The Phantom Planet', 
'Manos: The Hands of Fate', 
'Smash-Up, the Story of a Woman', 
'The Great Rupert', 
'The Little Shop of Horrors', 
'A Word to the Wives', 
'The Second Woman', 
'Scrub Me Mama with a Boogie Beat', 
'Orphans of the Storm', 
'Vengeance Valley', 
'The Jackie Robinson Story', 
'At War with the Army', 
'Atom Age Vampire', 
'Dementia 13', 
'King of the Zombies', 
'Carnival of Souls', 
'Jungle Jitters', 
'The Driller Killer', 
'Plan 9 from Outer Space', 
'Boy Meets Dog', 
'The Boy in the Plastic Bubble', 
'The Blood of Jesus', 
'The Giant Gila Monster', 
'The Phantom from 10,000 Leagues', 
'Creature from the Haunted Sea', 
'This Is the Army', 
'The Painted Hills', 
'Undersea Kingdom', 
'Topper Returns', 
'The Last Time I Saw Paris', 
'Swamp Women', 
'Hercules Unchained', 
'Horror Express', 
'Sex Madness', 
'Five Minutes to Live', 
'A Tale of Two Kitties', 
'The Cabinet of Dr. Caligari', 
'Santa Claus Conquers the Martians', 
'The Strange Love of Martha Ivers', 
'Bride of the Gorilla', 
'Queen of the Amazons', 
'My Favorite Brunette', 
'Lady Frankenstein', 
'The Eternal Jew', 
'The Ape', 
'Salt of the Earth', 
'Voyage to the Prehistoric Planet', 
'The World Gone Mad', 
'The Monster Maker', 
'Death Rides a Horse', 
'Rocketship X-M', 
'One Body Too Many', 
'Tarzan the Tiger', 
'The Poor Little Rich Girl', 
'A Coach for Cinderella', 
'Kansas City Confidential', 
'Bloody Pit of Horror', 
}
